### ISSUE TITLE
PBs count wrong

### ISSUE THREAD

**Issue by tyshoe** [mgmedick/SpeedRunCharts#12]
count of PBs is wrong. for the number displayed, it is actually 1 higher

**Comment by mgmedick** [comment]
Hi @tyshoe,

Appreciate your interest in the site and opening a ticket. I took a look at the code and I’m not seeing why the PB count would be off by 1, can you let me know why you think this is the case. The way the logic works is it counts the number of unique leaderboards (game/category/level/subcategory combinations) that you have a run for and that’s your PB count. This is because at least one of the runs under each leaderboard is guaranteed to be a PB (including your first run for that leaderboard).

What may have happened is one of your runs for a leaderboard was deleted or invalidated on the [speedrun.com](http://speedrun.com/) side, or the leaderboard itself was retired so it’s no longer in the count. So when you get a chance can you let me know where you got your PB count from that you’re using in comparison. It would be helpful if you happen to know what PB in particular you think is missing. Thanks again.

**Comment by mgmedick** [comment]
Hi @tyshoe,

Disregard that previous comment, I see how you got the PB count (by counting your non-obsolete runs on speedrun.com). Looking into it further I found this issue is due to your runs under "Turbo Overkill > Dead Plaza > Virgin Plaza" (see screenshots below). I was under the impression you can only have 1 ranked run under a particular leaderboard, so I don't understand how you can be both 1st and 3rd place. So unless I'm missing something this seems like a bug on speedrun.com. Let me know me know if I'm misunderstanding how that works.

<img width="714" alt="Screenshot 2023-02-19 at 12 15 48 AM" src="https://user-images.githubusercontent.com/6207440/219932325-92963d0f-9f3a-4665-88c3-9e6c4b99bbe2.png">

<img width="830" alt="Screenshot 2023-02-19 at 12 02 06 AM" src="https://user-images.githubusercontent.com/6207440/219932051-66f9af51-c7c3-4d71-8ada-6b797e716494.png">

**Comment by tyshoe** [comment]
@mgmedick This is undoubtedly the case, good catch.  This was actually a submission error on my part, because I do not own that game on PS4.  There is an option on speedrun.com for platforms to obsolete each other, which is turned off for turbo overkill.  Most leaderboards split platform runs if there are significant advantages to playing on one versus the other, like load times.  This advantage is not particularly present for Turbo Overkill especially given the number of people who run the game.  I wrote logic to count the runs for an app that I am building, but it didn't count top run by unique board, it just counted each appearance on each board.  I think its fair to close this issue, sorry for the misunderstanding.  Also, I love this project, good work.

**Comment by mgmedick** [comment]
Thanks @tyshoe, appreciate the followup.
